= Ken Anderson

== Publications

* Ken Anderson, "Tree Cache". Symposium on Combinatorial Search (SoCS). 2012.
* Kenneth Anderson, "link:docs/anderson2010additive.pdf[Additive Heuristic for Four-Connected Gridworlds]". Symposium on Combinatorial Search (SoCS). 2010.
* Larus Technologies & GE Fanuc Intelligent Platforms, "21st Century Territorial Security: a sensor networking approach", white paper, November 2008.
* M. Greenspan, J. Lam, W. Leckie, M. Godard, I. Zaidi, K. Anderson, D. Dupuis, and S. Jordan, "Toward a Competitive Pool Playing Robot", IEEE Computer Magazine, vol. 41(1):46-53, Jan. 2008.
* Kenneth Anderson, Nathan Sturtevant, Robert Holte, and Jonathan Schaeffer.  "link:docs/anderson2007coarseToFine_tech.pdf[Coarse-to-Fine Search Techniques]", Technical Report TR 08-05, 2008.
* Kenneth Anderson. "link:docs/anderson2007thesis.pdf[Memory and Abstraction used for Heuristics in Single-Agent Search]", M.Sc. Thesis, 2007.
* Kenneth Anderson, Robert Holte, and Jonathan Schaeffer. "link:docs/anderson2007ppdb.pdf[Partial Pattern Databases]". Symposium on Abstraction, Reformulation, and Approximation (SARA). Pages 20-34. Whistler, Canada. 2007.
* Michael Greenspan, Joseph Lam, Will Leckie, Marc Godard, Imran Zaidi, Ken Anderson, Donna Dupuis, and Sam Jordan. "Toward a Competitive Pool Playing Robot: Is Computational Intelligence Needed to Play Robotic Pool?" IEEE Symposium on Computational Intelligence and Games (CIG). Pages 380-388. Honolulu, Hawaii. 2007.
* D. Chris Rayner, Katherine Davison, Vadim Bulitko, Kenneth Anderson, and Jieshan Lu. "Real-Time Heuristic Search with a Priority Queue". International Joint Conference on Artificial Intelligence (IJCAI). Pages 2372-2377. Hyderabad, India. 2007.

